messages:
  prefix: '&5ABestCrates &8» &7'
  no-permission: '&cNie masz uprawnien.'
  player-only: '&cTa komenda jest tylko dla gracza.'
  player-offline: '&cGracz %player% nie jest online.'
  usage: '&cPoprawne uzycie: &f%usage%'
  reloaded: '&aPrzeladowano konfiguracje.'
  saved: '&aZapisano skrzynke.'
  crate-created: '&aStworzono skrzynke &f%crate%&a.'
  crate-deleted: '&aUsunieto skrzynke &f%crate%&a.'
  crate-exists: '&cSkrzynka &f%crate% &cjuz istnieje.'
  crate-missing: '&cNie znaleziono skrzynki &f%crate%&c.'
  crate-spawned: '&aPostawiono skrzynke &f%crate%&a w twojej lokalizacji.'
  crate-empty: '&cSkrzynka &f%crate% &cnie ma nagrod.'
  key-given: '&aDano &f%amount%x &aklucz do &f%crate% &adla &f%player%&a.'
  virtual-keys-added: '&aDodano &f%amount%x &awirtualne klucze do &f%crate% &adla &f%player%&a.'
  virtual-keys-removed: '&aUsunieto &f%amount%x &awirtualne klucze do &f%crate% &adla &f%player%&a.'
  reward-received: '&aWygrales &f%reward% &az &f%crate_displayname%&a.'
  reward-broadcast: '&5ABestCrates &8» &f%player% &7zdobyl &f%reward% &7z &f%crate_displayname%&7!'
  hold-item: '&cTrzymaj item w rece, aby dodac go jako nagrode.'
