package pl.admerpro.aBestCrates.gui;

public enum MenuType {
    MAIN,
    MANAGE,
    EDIT,
    REWARDS,
    REWARD_EDIT,
    REWARD_ITEMS,
    PREVIEW,
    OPENING,
    CHOOSE_OPEN,
    GIVE_KEY_TYPE,
    GIVE_KEY_CRATE,
    GIVE_KEY_PLAYER,
    ADMIN_TOOLS,
    STATS_MENU,
    STATS_PLAYER_SELECT,
    STATS_PLAYER_DETAIL,
    STATS_CRATE_SELECT,
    STATS_CRATE_DETAIL,
    STATS_POPULAR_CRATES,
    STATS_PLAYER_TOTALS
}
